apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ye6vrezqp-nodejs 
  janus-idp.io/tekton: ye6vrezqp-nodejs
  backstage.io/kubernetes-id: ye6vrezqp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ye6vrezqp-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml