apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ye6vrezqp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ye6vrezqp-nodejs 
  name: ye6vrezqp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ye6vrezqp-nodejs 
